spring.application.name=kyc
spring.config.import=optional:file:.env[.properties]


server.address=0.0.0.0
server.port=8080

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}


spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false

# server.port=8080

# JWT Configuration
app.jwtSecret=${JWT_SECRET}
app.jwtExpirationMs=${JWT_ExpirationMs}